# Легаси-таблица для tools/rs485_pace.py (только чтение). Единицы измерения здесь
# местами некорректны ('When'/'String'); актуальная таблица с русскими названиями
# и проверенными единицами — energybms-editor/energybms_editor/params.py.
PARAMS = [
  (0x00,2,'Cell over voltage alarm','0.001','V'),
  (0x01,2,'Cell over voltage alarm recovery','0.001','V'),
  (0x02,2,'Cell under voltage alarm','0.001','V'),
  (0x03,2,'Cell under voltage alarm recovery','0.001','V'),
  (0x04,2,'Cell over voltage protection','0.001','V'),
  (0x05,2,'Cell over voltage protection recovery','0.001','V'),
  (0x06,2,'Cell under voltage protection','0.001','V'),
  (0x07,2,'Cell under voltage protection recovery','0.001','V'),
  (0x08,2,'Balance turn-on voltage','0.001','V'),
  (0x09,2,'Battery low voltage forbidden charging','0.001','V'),
  (0x0A,2,'Pack over voltage alarm','0.01','V'),
  (0x0B,2,'Pack over voltage alarm recovery','0.01','V'),
  (0x0C,2,'Pack under voltage alarm','0.01','V'),
  (0x0D,2,'Pack under voltage alarm recovery','0.01','V'),
  (0x0E,2,'Pack over voltage protection','0.01','V'),
  (0x0F,2,'Pack over voltage protection recovery','0.01','V'),
  (0x10,2,'Pack under voltage protection','0.01','V'),
  (0x11,2,'Pack under voltage protection recovery','0.01','V'),
  (0x12,2,'Charging overvoltage protection','0.01','V'),
  (0x13,2,'Charging overvoltage recovery','0.01','V'),
  (0x14,2,'Charging over temperature alarm','0.1','℃'),
  (0x15,2,'Charging over temperature alarm recovery','0.1','℃'),
  (0x16,2,'Charging under temperature alarm','0.1','℃'),
  (0x17,2,'Charging under temperature alarm recovery','0.1','℃'),
  (0x18,2,'Charging over temperature protection','0.1','℃'),
  (0x19,2,'Charging over temperature protection recovery','0.1','℃'),
  (0x1A,2,'Charging under temperature protection','0.1','℃'),
  (0x1B,2,'Charging under temperature protection recovery','0.1','℃'),
  (0x1C,2,'Discharge over temperature alarm','0.1','℃'),
  (0x1D,2,'Discharge over temperature alarm recovery','0.1','℃'),
  (0x1E,2,'Discharge under temperature alarm','0.1','℃'),
  (0x1F,2,'Discharge under temperature alarm recovery','0.1','℃'),
  (0x20,2,'Discharge over temperature protection','0.1','℃'),
  (0x21,2,'Discharge over temperature protection recovery','0.1','℃'),
  (0x22,2,'Discharge under temperature protection','0.1','℃'),
  (0x23,2,'Discharge under temperature protection recovery','0.1','℃'),
  (0x24,2,'Cell low temperature heating','0.1','℃'),
  (0x25,2,'Cell heating recovery','0.1','℃'),
  (0x26,2,'Environmental over temperature alarm','0.1','℃'),
  (0x27,2,'Environmental over temperature alarm recovery','0.1','℃'),
  (0x28,2,'Environmental under temperature alarm','0.1','℃'),
  (0x29,2,'Environmental under temperature alarm recovery','0.1','℃'),
  (0x2A,2,'Environmental over temperature protection','0.1','℃'),
  (0x2B,2,'Environmental over temperature protection recovery','0.1','℃'),
  (0x2C,2,'Environmental under temperature protection','0.1','℃'),
  (0x2D,2,'Environmental under temperature protection recovery','0.1','℃'),
  (0x2E,2,'Power over temperature alarm','0.1','℃'),
  (0x2F,2,'Power over temperature alarm recovery','0.1','℃'),
  (0x30,2,'Power over temperature protection','0.1','℃'),
  (0x31,2,'Power over temperature protection recovery','0.1','℃'),
  (0x32,2,'Charging overcurrent alarm','0.01','A'),
  (0x33,2,'Charging overcurrent recovery','0.01','A'),
  (0x34,2,'Discharge overcurrent alarm','0.01','A'),
  (0x35,2,'Discharge overcurrent recovery','0.01','A'),
  (0x36,2,'Charge overcurrent protection','0.01','A'),
  (0x37,2,'Discharge overcurrent protection','0.01','A'),
  (0x38,2,'Transient overcurrent protection','0.01','A'),
  (0x39,2,'Output soft start delay','1','mS'),
  (0x3A,2,'Battery rated capacity','0.01','Ah'),
  (0x3B,2,'Remaining capacity','0.01','Ah'),
  (0x3C,1,'Voltage differential start','0.01','V'),
  (0x3D,1,'Voltage differential stop','0.01','V'),
  (0x3E,1,'Balance start voltage difference','0.001','V'),
  (0x3F,1,'Balance stop voltage difference','0.001','V'),
  (0x40,1,'Static equilibrium time','1','When'),
  (0x41,1,'Cell number','1','String'),
  (0x42,1,'Charge overcurrent delay','1','S'),
  (0x43,1,'Discharge overcurrent delay','1','S'),
  (0x44,1,'Transient overcurrent delay','1','mS'),
  (0x45,1,'Overcurrent delay recovery','1','S'),
  (0x46,1,'Overcurrent recovery times','1','times'),
  (0x47,1,'Charge current limit delay','1','Minutes'),
  (0x48,1,'Charge activation delay','1','Minutes'),
  (0x49,1,'Charging activation interval','1','When'),
  (0x4A,1,'Charge activation times','1','times'),
  (0x4B,1,'Work record interval','1','Minutes'),
  (0x4C,1,'Standby recording interval','1','Minutes'),
  (0x4D,1,'Standby shutdown delay','1','When'),
  (0x4E,1,'Remaining capacity alarm','1','%'),
  (0x4F,1,'Remaining capacity protection','1','%'),
  (0x50,1,'Interval charge capacity','1','%'),
  (0x51,1,'Cycle cumulative capacity','1','%'),
  (0x52,1,'Connection fault impedance','0.1','mΩ'),
  (0x53,1,'Compensation point 1 position','1','String'),
  (0x54,1,'Compensation point 1 impedance','0.1','mΩ'),
  (0x55,1,'Compensation point 2 position','1','String'),
  (0x56,1,'Compensation point 2 impedance','0.1','mΩ'),
]
BITGROUPS = {0: ['Voltage sensor invalidation', 'Temperature sensor invalidation', 'Current sensor invalidation', 'Button switch invalidation', 'Cell differential voltage invalidation', 'Charge switch invalidation', 'Discharge switch invalidation', 'Current limit switch invalidation'], 1: ['Cell over voltage alarm', 'Cell over voltage protection', 'Cell under voltage alarm', 'Cell under voltage protection', 'Pack over voltage alarm', 'Pack over voltage protection', 'Pack under voltage alarm', 'Pack under voltage protection'], 2: ['Charging over temperature alarm', 'Charging over temperature protection', 'Charging under temperature alarm', 'Charging under temperature protection', 'Discharge over temperature alarm', 'Discharge over temperature protection', 'Discharge under temperature alarm', 'Discharge under temperature protection'], 3: ['Environmental over temperature alarm', 'Environmental over temperature protection', 'Environmental under temperature alarm', 'Environmental under temperature protection', 'Power over temperature protection', 'Power over temperature alarm', 'Cell low temperature heating', 'Secondary tripping protection'], 4: ['Charging overcurrent alarm', 'Charge overcurrent protection', 'Discharge overcurrent alarm', 'Discharge overcurrent protection', 'Transient current protection', 'Output short circuit protection', 'Transient overcurrent lockout', 'Output short circuit locking'], 5: ['Charging high voltage protection', 'Intermittent charging function', 'Remaining capacity alarm', 'Remaining capacity protection', 'Battery low voltage forbidden charging', 'Output reverse connection protection', 'Aerosol failure', 'Output soft start function'], 6: ['Charge equalization function', 'Static equilibrium function', 'Timeout prohibits equalization', 'Over temperature prohibits equalization', 'Automatically activate charging', 'Manually activate charging', 'Take the initiative current limiting charging', 'Passive current limiting charging'], 7: ['Switch shut down function', 'Standby shutdown function', 'History record function', 'LCD display function', 'Bluetooth communication function', 'Automatic address coding', 'Parallel external polling', 'Single BMS 1.0C charging']}
